application: your-app-id-here
version: your-version-here
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:

# Various admin handlers
- url: /admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/appstats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  login: admin
  secure: always

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static
  login: admin
  secure: always

- url: /gae_mini_profiler/.*
  script: gae_mini_profiler.main.application
  login: admin
  secure: always

# General app handlers
- url: /static
  static_dir: dpxdt/server/static
  expiration: 1h
  secure: always

- url: .*
  script: main.application
  secure: always
