application: your-app-id-here
version: your-version-here
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  SQLALCHEMY_DATABASE_URI: mysql+gaerdbms:///test?instance=foo:bar
  CACHE_TYPE: memcached
  GOOGLE_CLOUD_STORAGE_BUCKET: fake-bucket-name-here/artifacts
  MAIL_USE_APPENGINE: True

builtins:
- appstats: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:

# Various admin handlers
- url: /admin(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: /_ah/appstats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  login: admin
  secure: always

# These only work if the gae_mini_profiler module is available
# - url: /gae_mini_profiler/static
#   static_dir: lib/gae_mini_profiler/static
#   login: admin
#   secure: always

# - url: /gae_mini_profiler/.*
#   script: gae_mini_profiler.main.application
#   login: admin
#   secure: always

# General app handlers
- url: /static
  static_dir: dpxdt/server/static
  expiration: 1h
  secure: always

- url: .*
  script: main.app


skip_files:
# These are default skip files values
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# NOTE: In production uncomment the line below. Don't upload Jinja2 by.
# The built-in module (from "libraries" above) has a c-extension that provides
# better debugging because it can parse stack frames. For local testing with
# dev_appserver this must be commented out.
# - ^(.*/)?lib/jinja2(/.*)?
